// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.35.1
// 	protoc        (unknown)
// source: jimmy/v1/migration.proto

package jimmyv1

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Environment int32

const (
	// All environments.
	Environment_ALL Environment = 0
	// The Google Cloud environment.
	Environment_GOOGLE_CLOUD Environment = 1
	// The emulator environment.
	Environment_EMULATOR Environment = 2
)

// Enum value maps for Environment.
var (
	Environment_name = map[int32]string{
		0: "ALL",
		1: "GOOGLE_CLOUD",
		2: "EMULATOR",
	}
	Environment_value = map[string]int32{
		"ALL":          0,
		"GOOGLE_CLOUD": 1,
		"EMULATOR":     2,
	}
)

func (x Environment) Enum() *Environment {
	p := new(Environment)
	*p = x
	return p
}

func (x Environment) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Environment) Descriptor() protoreflect.EnumDescriptor {
	return file_jimmy_v1_migration_proto_enumTypes[0].Descriptor()
}

func (Environment) Type() protoreflect.EnumType {
	return &file_jimmy_v1_migration_proto_enumTypes[0]
}

func (x Environment) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Environment.Descriptor instead.
func (Environment) EnumDescriptor() ([]byte, []int) {
	return file_jimmy_v1_migration_proto_rawDescGZIP(), []int{0}
}

type Type int32

const (
	// Automatically detect statement type.
	Type_AUTOMATIC Type = 0
	// The SQL is a DDL statement.
	Type_DDL Type = 1
	// The SQL is a DML statement.
	Type_DML Type = 2
	// The SQL is a partitioned DML statement.
	Type_PARTITIONED_DML Type = 3
)

// Enum value maps for Type.
var (
	Type_name = map[int32]string{
		0: "AUTOMATIC",
		1: "DDL",
		2: "DML",
		3: "PARTITIONED_DML",
	}
	Type_value = map[string]int32{
		"AUTOMATIC":       0,
		"DDL":             1,
		"DML":             2,
		"PARTITIONED_DML": 3,
	}
)

func (x Type) Enum() *Type {
	p := new(Type)
	*p = x
	return p
}

func (x Type) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Type) Descriptor() protoreflect.EnumDescriptor {
	return file_jimmy_v1_migration_proto_enumTypes[1].Descriptor()
}

func (Type) Type() protoreflect.EnumType {
	return &file_jimmy_v1_migration_proto_enumTypes[1]
}

func (x Type) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Type.Descriptor instead.
func (Type) EnumDescriptor() ([]byte, []int) {
	return file_jimmy_v1_migration_proto_rawDescGZIP(), []int{1}
}

// A SQL statement.
type Statement struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// A SQL statement to execute.
	Sql string `protobuf:"bytes,1,opt,name=sql,proto3" json:"sql,omitempty"`
	// The environment in which to run the statement.
	Env Environment `protobuf:"varint,2,opt,name=env,proto3,enum=jimmy.v1.Environment" json:"env,omitempty"`
	// The type of statement.
	Type Type `protobuf:"varint,3,opt,name=type,proto3,enum=jimmy.v1.Type" json:"type,omitempty"`
}

func (x *Statement) Reset() {
	*x = Statement{}
	mi := &file_jimmy_v1_migration_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Statement) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Statement) ProtoMessage() {}

func (x *Statement) ProtoReflect() protoreflect.Message {
	mi := &file_jimmy_v1_migration_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Statement.ProtoReflect.Descriptor instead.
func (*Statement) Descriptor() ([]byte, []int) {
	return file_jimmy_v1_migration_proto_rawDescGZIP(), []int{0}
}

func (x *Statement) GetSql() string {
	if x != nil {
		return x.Sql
	}
	return ""
}

func (x *Statement) GetEnv() Environment {
	if x != nil {
		return x.Env
	}
	return Environment_ALL
}

func (x *Statement) GetType() Type {
	if x != nil {
		return x.Type
	}
	return Type_AUTOMATIC
}

// A Jimmy migration file.
type Migration struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// The DDL statements to execute.
	Upgrade []*Statement `protobuf:"bytes,1,rep,name=upgrade,proto3" json:"upgrade,omitempty"`
	// The starting migration to squash.
	//
	// If the migration hasn't run yet then when an upgrade reaches
	// the squash ID it will jump directly to this migration,
	// skipping the in-between migrations.
	//
	// If the specified migration has already been run then this
	// migration will be skipped.
	SquashId *int32 `protobuf:"varint,2,opt,name=squash_id,json=squashId,proto3,oneof" json:"squash_id,omitempty"`
}

func (x *Migration) Reset() {
	*x = Migration{}
	mi := &file_jimmy_v1_migration_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Migration) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Migration) ProtoMessage() {}

func (x *Migration) ProtoReflect() protoreflect.Message {
	mi := &file_jimmy_v1_migration_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Migration.ProtoReflect.Descriptor instead.
func (*Migration) Descriptor() ([]byte, []int) {
	return file_jimmy_v1_migration_proto_rawDescGZIP(), []int{1}
}

func (x *Migration) GetUpgrade() []*Statement {
	if x != nil {
		return x.Upgrade
	}
	return nil
}

func (x *Migration) GetSquashId() int32 {
	if x != nil && x.SquashId != nil {
		return *x.SquashId
	}
	return 0
}

var File_jimmy_v1_migration_proto protoreflect.FileDescriptor

var file_jimmy_v1_migration_proto_rawDesc = []byte{
	0x0a, 0x18, 0x6a, 0x69, 0x6d, 0x6d, 0x79, 0x2f, 0x76, 0x31, 0x2f, 0x6d, 0x69, 0x67, 0x72, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x08, 0x6a, 0x69, 0x6d, 0x6d,
	0x79, 0x2e, 0x76, 0x31, 0x1a, 0x1b, 0x62, 0x75, 0x66, 0x2f, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x61,
	0x74, 0x65, 0x2f, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x22, 0x72, 0x0a, 0x09, 0x53, 0x74, 0x61, 0x74, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x12, 0x18,
	0x0a, 0x03, 0x73, 0x71, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x42, 0x06, 0xba, 0x48, 0x03,
	0xc8, 0x01, 0x01, 0x52, 0x03, 0x73, 0x71, 0x6c, 0x12, 0x27, 0x0a, 0x03, 0x65, 0x6e, 0x76, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x15, 0x2e, 0x6a, 0x69, 0x6d, 0x6d, 0x79, 0x2e, 0x76, 0x31,
	0x2e, 0x45, 0x6e, 0x76, 0x69, 0x72, 0x6f, 0x6e, 0x6d, 0x65, 0x6e, 0x74, 0x52, 0x03, 0x65, 0x6e,
	0x76, 0x12, 0x22, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0e, 0x32,
	0x0e, 0x2e, 0x6a, 0x69, 0x6d, 0x6d, 0x79, 0x2e, 0x76, 0x31, 0x2e, 0x54, 0x79, 0x70, 0x65, 0x52,
	0x04, 0x74, 0x79, 0x70, 0x65, 0x22, 0x6a, 0x0a, 0x09, 0x4d, 0x69, 0x67, 0x72, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x12, 0x2d, 0x0a, 0x07, 0x75, 0x70, 0x67, 0x72, 0x61, 0x64, 0x65, 0x18, 0x01, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x6a, 0x69, 0x6d, 0x6d, 0x79, 0x2e, 0x76, 0x31, 0x2e, 0x53,
	0x74, 0x61, 0x74, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x52, 0x07, 0x75, 0x70, 0x67, 0x72, 0x61, 0x64,
	0x65, 0x12, 0x20, 0x0a, 0x09, 0x73, 0x71, 0x75, 0x61, 0x73, 0x68, 0x5f, 0x69, 0x64, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x05, 0x48, 0x00, 0x52, 0x08, 0x73, 0x71, 0x75, 0x61, 0x73, 0x68, 0x49, 0x64,
	0x88, 0x01, 0x01, 0x42, 0x0c, 0x0a, 0x0a, 0x5f, 0x73, 0x71, 0x75, 0x61, 0x73, 0x68, 0x5f, 0x69,
	0x64, 0x2a, 0x36, 0x0a, 0x0b, 0x45, 0x6e, 0x76, 0x69, 0x72, 0x6f, 0x6e, 0x6d, 0x65, 0x6e, 0x74,
	0x12, 0x07, 0x0a, 0x03, 0x41, 0x4c, 0x4c, 0x10, 0x00, 0x12, 0x10, 0x0a, 0x0c, 0x47, 0x4f, 0x4f,
	0x47, 0x4c, 0x45, 0x5f, 0x43, 0x4c, 0x4f, 0x55, 0x44, 0x10, 0x01, 0x12, 0x0c, 0x0a, 0x08, 0x45,
	0x4d, 0x55, 0x4c, 0x41, 0x54, 0x4f, 0x52, 0x10, 0x02, 0x2a, 0x3c, 0x0a, 0x04, 0x54, 0x79, 0x70,
	0x65, 0x12, 0x0d, 0x0a, 0x09, 0x41, 0x55, 0x54, 0x4f, 0x4d, 0x41, 0x54, 0x49, 0x43, 0x10, 0x00,
	0x12, 0x07, 0x0a, 0x03, 0x44, 0x44, 0x4c, 0x10, 0x01, 0x12, 0x07, 0x0a, 0x03, 0x44, 0x4d, 0x4c,
	0x10, 0x02, 0x12, 0x13, 0x0a, 0x0f, 0x50, 0x41, 0x52, 0x54, 0x49, 0x54, 0x49, 0x4f, 0x4e, 0x45,
	0x44, 0x5f, 0x44, 0x4d, 0x4c, 0x10, 0x03, 0x42, 0x94, 0x01, 0x0a, 0x0c, 0x63, 0x6f, 0x6d, 0x2e,
	0x6a, 0x69, 0x6d, 0x6d, 0x79, 0x2e, 0x76, 0x31, 0x42, 0x0e, 0x4d, 0x69, 0x67, 0x72, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x50, 0x01, 0x5a, 0x33, 0x67, 0x69, 0x74, 0x68,
	0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x73, 0x69, 0x6c, 0x61, 0x73, 0x2f, 0x6a, 0x69, 0x6d,
	0x6d, 0x79, 0x2f, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x70, 0x62, 0x2f, 0x6a,
	0x69, 0x6d, 0x6d, 0x79, 0x2f, 0x76, 0x31, 0x3b, 0x6a, 0x69, 0x6d, 0x6d, 0x79, 0x76, 0x31, 0xa2,
	0x02, 0x03, 0x4a, 0x58, 0x58, 0xaa, 0x02, 0x08, 0x4a, 0x69, 0x6d, 0x6d, 0x79, 0x2e, 0x56, 0x31,
	0xca, 0x02, 0x08, 0x4a, 0x69, 0x6d, 0x6d, 0x79, 0x5c, 0x56, 0x31, 0xe2, 0x02, 0x14, 0x4a, 0x69,
	0x6d, 0x6d, 0x79, 0x5c, 0x56, 0x31, 0x5c, 0x47, 0x50, 0x42, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61,
	0x74, 0x61, 0xea, 0x02, 0x09, 0x4a, 0x69, 0x6d, 0x6d, 0x79, 0x3a, 0x3a, 0x56, 0x31, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_jimmy_v1_migration_proto_rawDescOnce sync.Once
	file_jimmy_v1_migration_proto_rawDescData = file_jimmy_v1_migration_proto_rawDesc
)

func file_jimmy_v1_migration_proto_rawDescGZIP() []byte {
	file_jimmy_v1_migration_proto_rawDescOnce.Do(func() {
		file_jimmy_v1_migration_proto_rawDescData = protoimpl.X.CompressGZIP(file_jimmy_v1_migration_proto_rawDescData)
	})
	return file_jimmy_v1_migration_proto_rawDescData
}

var file_jimmy_v1_migration_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_jimmy_v1_migration_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_jimmy_v1_migration_proto_goTypes = []any{
	(Environment)(0),  // 0: jimmy.v1.Environment
	(Type)(0),         // 1: jimmy.v1.Type
	(*Statement)(nil), // 2: jimmy.v1.Statement
	(*Migration)(nil), // 3: jimmy.v1.Migration
}
var file_jimmy_v1_migration_proto_depIdxs = []int32{
	0, // 0: jimmy.v1.Statement.env:type_name -> jimmy.v1.Environment
	1, // 1: jimmy.v1.Statement.type:type_name -> jimmy.v1.Type
	2, // 2: jimmy.v1.Migration.upgrade:type_name -> jimmy.v1.Statement
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_jimmy_v1_migration_proto_init() }
func file_jimmy_v1_migration_proto_init() {
	if File_jimmy_v1_migration_proto != nil {
		return
	}
	file_jimmy_v1_migration_proto_msgTypes[1].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_jimmy_v1_migration_proto_rawDesc,
			NumEnums:      2,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_jimmy_v1_migration_proto_goTypes,
		DependencyIndexes: file_jimmy_v1_migration_proto_depIdxs,
		EnumInfos:         file_jimmy_v1_migration_proto_enumTypes,
		MessageInfos:      file_jimmy_v1_migration_proto_msgTypes,
	}.Build()
	File_jimmy_v1_migration_proto = out.File
	file_jimmy_v1_migration_proto_rawDesc = nil
	file_jimmy_v1_migration_proto_goTypes = nil
	file_jimmy_v1_migration_proto_depIdxs = nil
}
