run:
  go: "1.23"
  timeout: 5m

linters-settings:
  forbidigo:
    forbid:
      - ^print.*$
      - 'fmt\.Print.*'
  gci:
    sections:
      - standard
      - default
      - prefix(github.com/silas/jimmy)
      - blank
      - dot
    custom-order: true
  gofmt:
    rewrite-rules:
      - pattern: "interface{}"
        replacement: "any"
  stylecheck:
    checks: ["all"]
  testifylint:
    enable-all: true

linters:
  enable:
    - forbidigo
    - gci
    - gofmt
    - goimports
    - misspell
    - nilerr
    - stylecheck
    - testifylint
    - testpackage
